### ISSUE TITLE
dependency broken?

### ISSUE THREAD

**Issue by Daniel-Pivonka** [enrichman/androidmail#1]
compile 'it.enricocandino:androidmail:1.0.0-SNAPSHOT' 

does not compile unable to resolve

**Comment by enrichman** [comment]
Hi Daniel, which is the error that you got?

**Comment by Daniel-Pivonka** [comment]
when i include " compile 'it.enricocandino:androidmail:1.0.0-SNAPSHOT' " in my app gradle under dependencies and i sync the gradle i get the error below

Error:(28, 13) Failed to resolve: it.enricocandino:androidmail:1.0.0-SNAPSHOT

**Comment by enrichman** [comment]
Hm, did you add the mavenCentral repository to your `build.gradle`?

```gradle
buildscript {
    repositories {
        jcenter()
        mavenCentral()
    }
    ...
}

allprojects {
    repositories {
        jcenter()
        mavenCentral()
        maven {
            url "https://oss.sonatype.org/content/groups/public"
        }
    }
}
```

I thought it was in the sample app but I was wrong.  
It's better to specify this in the README.  
And I probably should upload the .aar also to bintray!

Let me know if it was this the problem!

**Comment by Daniel-Pivonka** [comment]
Yes that worked. thank you
