### ISSUE TITLE
compile 'it.enricocandino:androidmail:1.0.0-SNAPSHOT' not found

### ISSUE THREAD

**Issue by Paul75** [enrichman/androidmail#2]
Hello,

compile 'it.enricocandino:androidmail:1.0.0-SNAPSHOT'

not found.

**Comment by enrichman** [comment]
Hi @Paul75, could you check if this is the same issue? https://github.com/enrichman/androidmail/issues/1

**Comment by Paul75** [comment]
the same issue

**Comment by enrichman** [comment]
Yes, sorry, I should update the documentation.

So have you resolved? Can I close this?

**Comment by Paul75** [comment]
Yes it can close. Thanks solve it

**Comment by enrichman** [comment]
Let me know if you have any other problems. :+1:

**Comment by Paul75** [comment]
just a question : you application use gmail account to send ?
in :
MailSender mailSender = new MailSender(email, password);

the email is gmail ?

Thanks

**Comment by enrichman** [comment]
Yes, you have to use something like "mymail@gmail.com".

If Google haven't changed anything it should work (maybe with a warning).
