### ISSUE TITLE
Received status code 403 from server: Forbidden

### ISSUE THREAD

**Issue by shlomo-edu** [enrichman/androidmail#3]
I receive the following error:
`Could not GET 'https://dl.bintray.com/fourier-edu/Android-Fourier-Education/it/enricocandino/androidmail/1.0.0-SNAPSHOT/maven-metadata.xml'. Received status code 403 from server: Forbidden
Disable Gradle 'offline mode' and sync project
`

I added this as you described in Issue: #1

`buildscript {
    repositories {
        jcenter()
        mavenCentral()
    }
}

allprojects {
    repositories {
        jcenter()
        mavenCentral()
        maven {
            url "https://oss.sonatype.org/content/groups/public"
        }
    }
}
`
and 
`   implementation 'it.enricocandino:androidmail:1.0.0-SNAPSHOT';
`

**Comment by shlomo-edu** [comment]
OK, I did 
File -> Validate and Resart
and it solved the problem.

**Comment by enrichman** [comment]
Glad you solved the problem! Closing. :smile:
